# Generated by Django 4.2.1 on 2023-06-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='dv',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dv'),
        ),
    ]
