# Generated by Django 4.2.1 on 2023-06-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0002_alter_producto_dv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
